// Auto-generated by gen_bp_data_js.py
// Data Date: 2026-08-28 (latest BRT)
// Updated: 2026-08-29
// ============================================================

export const dataMeta = {
  dataDate: "2026-08-28",
  updatedDate: "2026-08-29",
};

// ── KPI Cards ──────────────────────────────────────────────
export const kpiCards = {
  totalOrders10d: 650755,
  totalNewSigns10d: 79,
  totalGMV10d: 4182403.84,
  avgAOV: 47.72,
};

// ── Daily Orders (10 days) ─────────────────────────────────
export const dailyOrders = [
  {
    "date": "2026-08-28",
    "total": 89677
  },
  {
    "date": "2026-08-27",
    "total": 55081
  },
  {
    "date": "2026-08-26",
    "total": 49624
  },
  {
    "date": "2026-08-25",
    "total": 46582
  },
  {
    "date": "2026-08-24",
    "total": 42732
  },
  {
    "date": "2026-08-23",
    "total": 75393
  },
  {
    "date": "2026-08-22",
    "total": 89394
  },
  {
    "date": "2026-08-21",
    "total": 88118
  },
  {
    "date": "2026-08-20",
    "total": 60671
  },
  {
    "date": "2026-08-19",
    "total": 53483
  }
];

// ── New Signs by Priority ──────────────────────────────────
export const newSigns = [
  {
    "date": "2026-08-28",
    "topTier": 3,
    "midTier": 1,
    "mustHave": 0,
    "total": 4
  },
  {
    "date": "2026-08-27",
    "topTier": 6,
    "midTier": 3,
    "mustHave": 2,
    "total": 11
  },
  {
    "date": "2026-08-26",
    "topTier": 7,
    "midTier": 2,
    "mustHave": 0,
    "total": 9
  },
  {
    "date": "2026-08-25",
    "topTier": 6,
    "midTier": 4,
    "mustHave": 1,
    "total": 11
  },
  {
    "date": "2026-08-24",
    "topTier": 5,
    "midTier": 4,
    "mustHave": 0,
    "total": 9
  },
  {
    "date": "2026-08-23",
    "topTier": 1,
    "midTier": 0,
    "mustHave": 0,
    "total": 1
  },
  {
    "date": "2026-08-22",
    "topTier": 0,
    "midTier": 3,
    "mustHave": 0,
    "total": 3
  },
  {
    "date": "2026-08-21",
    "topTier": 8,
    "midTier": 3,
    "mustHave": 0,
    "total": 11
  },
  {
    "date": "2026-08-20",
    "topTier": 3,
    "midTier": 2,
    "mustHave": 2,
    "total": 7
  },
  {
    "date": "2026-08-19",
    "topTier": 8,
    "midTier": 3,
    "mustHave": 2,
    "total": 13
  }
];

// ── CM Business Performance (latest date = 2026-08-28) ─────
export const cmBusiness = [
  {
    "region": "Central Eestern Region",
    "city": "S\u00e3o Paulo City A",
    "orders": 9,
    "aov": 44.47,
    "gmv": 400.27,
    "storeAvg": 4.5
  },
  {
    "region": "Central Eestern Region",
    "city": "S\u00e3o Paulo City B",
    "orders": 158,
    "aov": 43.36,
    "gmv": 6851.59,
    "storeAvg": 158.0
  },
  {
    "region": "Central Eestern Region",
    "city": "S\u00e3o Paulo City D",
    "orders": 5,
    "aov": 60.81,
    "gmv": 304.06,
    "storeAvg": 2.5
  },
  {
    "region": "Central Western Region",
    "city": "S\u00e3o Paulo City C",
    "orders": 16,
    "aov": 35.49,
    "gmv": 567.87,
    "storeAvg": 16.0
  },
  {
    "region": "Central Western Region",
    "city": "S\u00e3o Paulo City E",
    "orders": 51,
    "aov": 48.46,
    "gmv": 2471.48,
    "storeAvg": 5.1
  },
  {
    "region": "Central Western Region",
    "city": "S\u00e3o Paulo City F",
    "orders": 15,
    "aov": 41.03,
    "gmv": 615.51,
    "storeAvg": 7.5
  },
  {
    "region": "Metropolitan Region",
    "city": "Overall",
    "orders": 34030,
    "aov": 47.57,
    "gmv": 1618895.93,
    "storeAvg": 15.07
  },
  {
    "region": "Metropolitan Region",
    "city": "Northeast S\u00e3o Paulo Metropolitan",
    "orders": 45186,
    "aov": 47.66,
    "gmv": 2153705.62,
    "storeAvg": 15.17
  },
  {
    "region": "Metropolitan Region",
    "city": "Santos City",
    "orders": 8169,
    "aov": 48.79,
    "gmv": 398591.51,
    "storeAvg": 12.93
  }
];

// ── Promotion Coverage ─────────────────────────────────────
export const promotion = [
  {
    "date": "2026-08-28",
    "deepDiscount": 0.7647,
    "fullDiscount": 0.2995,
    "deliveryDiscount": 0.9387
  },
  {
    "date": "2026-08-27",
    "deepDiscount": 0.766,
    "fullDiscount": 0.3003,
    "deliveryDiscount": 0.9386
  },
  {
    "date": "2026-08-26",
    "deepDiscount": 0.7656,
    "fullDiscount": 0.3007,
    "deliveryDiscount": 0.9377
  },
  {
    "date": "2026-08-25",
    "deepDiscount": 0.7637,
    "fullDiscount": 0.2969,
    "deliveryDiscount": 0.9347
  },
  {
    "date": "2026-08-24",
    "deepDiscount": 0.7655,
    "fullDiscount": 0.3014,
    "deliveryDiscount": 0.9375
  },
  {
    "date": "2026-08-23",
    "deepDiscount": 0.7576,
    "fullDiscount": 0.3068,
    "deliveryDiscount": 0.9381
  },
  {
    "date": "2026-08-22",
    "deepDiscount": 0.7544,
    "fullDiscount": 0.3006,
    "deliveryDiscount": 0.9386
  },
  {
    "date": "2026-08-21",
    "deepDiscount": 0.7588,
    "fullDiscount": 0.2976,
    "deliveryDiscount": 0.9389
  },
  {
    "date": "2026-08-20",
    "deepDiscount": 0.7564,
    "fullDiscount": 0.299,
    "deliveryDiscount": 0.948
  },
  {
    "date": "2026-08-19",
    "deepDiscount": 0.7516,
    "fullDiscount": 0.2973,
    "deliveryDiscount": 0.9493
  }
];

// ── User Experience ────────────────────────────────────────
export const userExperience = [];

// ── Operation Performance (Op Rate by Priority) ────────────
export const operationPerf = [];

// ── Backward compat exports (keep existing pages working) ──
export const regionTargets = { topMH: 201, mid: 270, mhActiveRate: 80.8, topActiveRate: 90.6, activeRate: 60, cancelRate: 1.5, discountCoverage: 65 };
export const regionActuals = { topMH: 0, mid: 0, mhActiveRate: null, topActiveRate: null, activeRate: null, cancelRate: null, discountCoverage: null };
export const regionOps = { dailyOrders: 0, wow: "" };
export const ddTargets = { mh1dd: 65, mh3dd: 30, tm1dd: 50, tm3dd: 30 };
export const ddActuals = { mh1dd: null, mh3dd: null, tm1dd: null, tm3dd: null };

export const dailyData = [];

export const dbrReport = {
  "dataDate": "2026-08-28",
  "kpis": {
    "dailyOrders": {
      "value": 89677,
      "wow": "",
      "wowPositiveIsGood": true
    },
    "dailyGMV": {
      "value": 0,
      "wow": "",
      "wowPositiveIsGood": true
    },
    "cancelRate": {
      "value": null,
      "wow": "",
      "wowPositiveIsGood": false
    },
    "activeRate": {
      "value": null,
      "wow": null,
      "wowPositiveIsGood": true
    }
  },
  "cities": [
    {
      "city": "Northeast",
      "cm": "Daniel",
      "dailyOrders": 0,
      "ordersWow": "",
      "gmv": 0,
      "gmvWow": "",
      "aov": 0,
      "newSignTopDaily": 0,
      "newSignMidDaily": 0,
      "newSignTopMTD": 0,
      "newSignMidMTD": 0,
      "activeRate": null,
      "cancelRate": null,
      "cancelRateWow": ""
    },
    {
      "city": "Southern",
      "cm": "Tian Jie",
      "dailyOrders": 0,
      "ordersWow": "",
      "gmv": 0,
      "gmvWow": "",
      "aov": 0,
      "newSignTopDaily": 0,
      "newSignMidDaily": 0,
      "newSignTopMTD": 0,
      "newSignMidMTD": 0,
      "activeRate": null,
      "cancelRate": null,
      "cancelRateWow": ""
    },
    {
      "city": "Western",
      "cm": "Feng Menglong",
      "dailyOrders": 0,
      "ordersWow": "",
      "gmv": 0,
      "gmvWow": "",
      "aov": 0,
      "newSignTopDaily": 0,
      "newSignMidDaily": 0,
      "newSignTopMTD": 0,
      "newSignMidMTD": 0,
      "activeRate": null,
      "cancelRate": null,
      "cancelRateWow": ""
    },
    {
      "city": "Santos",
      "cm": "Jaylin",
      "dailyOrders": 0,
      "ordersWow": "",
      "gmv": 0,
      "gmvWow": "",
      "aov": 0,
      "newSignTopDaily": 0,
      "newSignMidDaily": 0,
      "newSignTopMTD": 0,
      "newSignMidMTD": 0,
      "activeRate": null,
      "cancelRate": null,
      "cancelRateWow": ""
    }
  ],
  "metroTotal": {
    "dailyOrders": 89677,
    "ordersWow": "",
    "gmv": 0,
    "gmvWow": "",
    "aov": 0,
    "newSignTopDaily": 0,
    "newSignMidDaily": 0,
    "newSignTopMTD": 0,
    "newSignMidMTD": 0,
    "activeRate": null,
    "cancelRate": null,
    "cancelRateWow": ""
  },
  "insights": [
    {
      "icon": "\ud83d\udcc8",
      "text": "Metro total orders 89677 WoW (latest)."
    },
    {
      "icon": "\ud83c\udfea",
      "text": "New sign yesterday: 3 Top + 1 Mid = 4 total."
    }
  ]
};


export const ddData = {
  date: "2026-08-28",
  targets: { mh: { dd3_15: 0.3, dd1_15: 0.65 }, all: { dd3_15: 0.3, dd1_15: 0.5 } },
  metro: { mh: { shops: null, dd3_15_count: null, dd1_15_count: null, dd3_40_count: null, dd1_40_count: null, dd3_15: null, dd1_15: null, dd3_40: null, dd1_40: null }, all: { shops: null, dd3_15_count: null, dd1_15_count: null, dd3_40_count: null, dd1_40_count: null, dd3_15: null, dd1_15: null, dd3_40: null, dd1_40: null } },
  cities: {
    northeast: { label: "Northeast", labelCn: "东北区", cm: "danielalbuquerque", mh: { shops: null, dd3_15_count: null, dd1_15_count: null, dd3_40_count: null, dd1_40_count: null, dd3_15: null, dd1_15: null, dd3_40: null, dd1_40: null }, all: { shops: null, dd3_15_count: null, dd1_15_count: null, dd3_40_count: null, dd1_40_count: null, dd3_15: null, dd1_15: null, dd3_40: null, dd1_40: null }, bdms: [] },
    western: { label: "Western", labelCn: "西区", cm: "fengmenglong", mh: { shops: null, dd3_15_count: null, dd1_15_count: null, dd3_40_count: null, dd1_40_count: null, dd3_15: null, dd1_15: null, dd3_40: null, dd1_40: null }, all: { shops: null, dd3_15_count: null, dd1_15_count: null, dd3_40_count: null, dd1_40_count: null, dd3_15: null, dd1_15: null, dd3_40: null, dd1_40: null }, bdms: [] },
    santos: { label: "Santos", labelCn: "桑托斯", cm: "jaylin", mh: { shops: null, dd3_15_count: null, dd1_15_count: null, dd3_40_count: null, dd1_40_count: null, dd3_15: null, dd1_15: null, dd3_40: null, dd1_40: null }, all: { shops: null, dd3_15_count: null, dd1_15_count: null, dd3_40_count: null, dd1_40_count: null, dd3_15: null, dd1_15: null, dd3_40: null, dd1_40: null }, bdms: [] },
    southern: { label: "Southern", labelCn: "南区", cm: "tianjie", mh: { shops: null, dd3_15_count: null, dd1_15_count: null, dd3_40_count: null, dd1_40_count: null, dd3_15: null, dd1_15: null, dd3_40: null, dd1_40: null }, all: { shops: null, dd3_15_count: null, dd1_15_count: null, dd3_40_count: null, dd1_40_count: null, dd3_15: null, dd1_15: null, dd3_40: null, dd1_40: null }, bdms: [] },
  }
};
