#!/usr/bin/env python3
"""Generate data.js for BP dashboard from bi_raw_data.json"""
import json
from collections import defaultdict
from datetime import datetime

with open('/mnt/openclaw/.openclaw/workspace/bi_raw_data.json', 'r') as f:
    data = json.load(f)

def fmt_date(s):
    return f"{s[:4]}-{s[4:6]}-{s[6:]}"

# ── Order Performance ──
op_raw = data['Last 10 Days - Order Performance']['data']['data']
orders_by_date = defaultdict(int)
for row in op_raw:
    orders_by_date[row[0]] += int(row[2])
daily_orders = [{"date": fmt_date(d), "total": orders_by_date[d]} for d in sorted(orders_by_date.keys(), reverse=True)]

# ── New Signs ──
sign_raw = data['Last 10 days - New Signs']['data']['data']
signs_by_date = defaultdict(dict)
for row in sign_raw:
    date, prio, val = row[0], row[1], int(row[2])
    signs_by_date[date][prio] = val

new_signs = []
for d in sorted(signs_by_date.keys(), reverse=True):
    s = signs_by_date[d]
    new_signs.append({
        "date": fmt_date(d),
        "topTier": s.get('Top-Tier', 0),
        "midTier": s.get('Mid-Tier', 0),
        "mustHave": s.get('Must-have', 0),
        "total": sum(s.values())
    })

# ── CM Business Performance ──
cm_raw = data['CM - Business Performance']['data']['data']
cm_rows = []
for row in cm_raw:
    def safe_float(v):
        try:
            f = float(v)
            return f if f == f else 0.0  # nan check
        except:
            return 0.0
    cm_rows.append({
        "region": row[1],
        "city": row[2] if row[2] != 'NULL' else 'Overall',
        "orders": int(row[3]) if row[3] else 0,
        "aov": round(safe_float(row[4]), 2),
        "gmv": round(safe_float(row[5]), 2),
        "storeAvg": round(safe_float(row[6]), 2),
    })

# ── Promotion ──
promo_raw = data['Last 10 days - Promotion']['data']['data']
promotion = []
for row in promo_raw:
    promotion.append({
        "date": fmt_date(row[0]),
        "deepDiscount": round(float(row[1]), 4),
        "fullDiscount": round(float(row[2]), 4),
        "deliveryDiscount": round(float(row[3]), 4),
    })
promotion = sorted(promotion, key=lambda x: x['date'], reverse=True)

# ── User Experience ──
ux = []
if 'Last 10 days - User Experience' in data:
    ux_raw = data['Last 10 days - User Experience']['data']['data']
    for row in ux_raw:
        ux.append({
            "date": fmt_date(row[0]),
            "cancelRate": round(float(row[1]), 4),
            "spillDamage": round(float(row[2]), 4),
            "missingWrong": round(float(row[3]), 4),
        })
    ux = sorted(ux, key=lambda x: x['date'], reverse=True)

# ── Operation Performance ──
op2_raw = data['Last 10 days - Operation Performance']['data']['data']
op_by_date = defaultdict(dict)
for row in op2_raw:
    date, prio, val = row[0], row[1], float(row[2])
    op_by_date[date][prio] = val

operation_perf = []
for d in sorted(op_by_date.keys(), reverse=True):
    o = op_by_date[d]
    operation_perf.append({
        "date": fmt_date(d),
        "topTier": round(o.get('Top-Tier', 0), 4),
        "midTier": round(o.get('Mid-Tier', 0), 4),
        "mustHave": round(o.get('Must-have', 0), 4),
    })

# ── KPI Summary ──
total_orders_10d = sum(orders_by_date.values())
total_new_signs_10d = sum(sum(s.values()) for s in signs_by_date.values())
total_gmv_10d = round(sum(r['gmv'] for r in cm_rows), 2)
# weighted AOV
total_orders_cm = sum(r['orders'] for r in cm_rows)
weighted_aov = round(sum(r['aov'] * r['orders'] for r in cm_rows) / total_orders_cm, 2) if total_orders_cm > 0 else 0

latest_date = max(orders_by_date.keys()) if orders_by_date else 'N/A'
latest_date_fmt = fmt_date(latest_date)

# Generate JS
lines = [
    "// Auto-generated by gen_bp_data_js.py",
    f"// Data Date: {latest_date_fmt} (latest BRT)",
    f"// Updated: {datetime.now().strftime('%Y-%m-%d')}",
    "// ============================================================",
    "",
    "export const dataMeta = {",
    f'  dataDate: "{latest_date_fmt}",',
    f'  updatedDate: "{datetime.now().strftime("%Y-%m-%d")}",',
    "};",
    "",
    "// ── KPI Cards ──────────────────────────────────────────────",
    "export const kpiCards = {",
    f"  totalOrders10d: {total_orders_10d},",
    f"  totalNewSigns10d: {total_new_signs_10d},",
    f"  totalGMV10d: {total_gmv_10d},",
    f"  avgAOV: {weighted_aov},",
    "};",
    "",
    "// ── Daily Orders (10 days) ─────────────────────────────────",
    "export const dailyOrders = " + json.dumps(daily_orders, indent=2) + ";",
    "",
    "// ── New Signs by Priority ──────────────────────────────────",
    "export const newSigns = " + json.dumps(new_signs, indent=2) + ";",
    "",
    f"// ── CM Business Performance (latest date = {latest_date_fmt}) ─────",
    "export const cmBusiness = " + json.dumps(cm_rows, indent=2) + ";",
    "",
    "// ── Promotion Coverage ─────────────────────────────────────",
    "export const promotion = " + json.dumps(promotion, indent=2) + ";",
    "",
    "// ── User Experience ────────────────────────────────────────",
    "export const userExperience = " + json.dumps(ux, indent=2) + ";",
    "",
    "// ── Operation Performance (Op Rate by Priority) ────────────",
    "export const operationPerf = " + json.dumps(operation_perf, indent=2) + ";",
    "",
]

# Add backward compat exports (keep existing pages working)
lines.extend([
    "// ── Backward compat exports (keep existing pages working) ──",
    "export const regionTargets = { topMH: 201, mid: 270, mhActiveRate: 80.8, topActiveRate: 90.6, activeRate: 60, cancelRate: 1.5, discountCoverage: 65 };",
    "export const regionActuals = { topMH: 0, mid: 0, mhActiveRate: null, topActiveRate: null, activeRate: null, cancelRate: null, discountCoverage: null };",
    "export const regionOps = { dailyOrders: 0, wow: \"\" };",
    "export const ddTargets = { mh1dd: 65, mh3dd: 30, tm1dd: 50, tm3dd: 30 };",
    "export const ddActuals = { mh1dd: null, mh3dd: null, tm1dd: null, tm3dd: null };",
    "",
])

# Keep static city/BDM data
with open('/mnt/openclaw/.openclaw/workspace/bp_data_20260827.js', 'r') as f:
    old_js = f.read()

# Extract cities export
import re
cities_match = re.search(r'export const cities = \[.*?\];', old_js, re.DOTALL)
if cities_match:
    lines.append(cities_match.group() + "\n")

bdm_match = re.search(r'export const bdmData = \{.*?\};', old_js, re.DOTALL)
if bdm_match:
    lines.append(bdm_match.group() + "\n")

lines.extend([
    "export const dailyData = [];",
    "",
])

# dbrReport with updated date
dbr = {
    "dataDate": latest_date_fmt,
    "kpis": {
        "dailyOrders": {"value": daily_orders[0]['total'] if daily_orders else 0, "wow": "", "wowPositiveIsGood": True},
        "dailyGMV": {"value": 0, "wow": "", "wowPositiveIsGood": True},
        "cancelRate": {"value": None, "wow": "", "wowPositiveIsGood": False},
        "activeRate": {"value": None, "wow": None, "wowPositiveIsGood": True},
    },
    "cities": [
        {"city": "Northeast", "cm": "Daniel", "dailyOrders": 0, "ordersWow": "", "gmv": 0, "gmvWow": "", "aov": 0, "newSignTopDaily": 0, "newSignMidDaily": 0, "newSignTopMTD": 0, "newSignMidMTD": 0, "activeRate": None, "cancelRate": None, "cancelRateWow": ""},
        {"city": "Southern", "cm": "Tian Jie", "dailyOrders": 0, "ordersWow": "", "gmv": 0, "gmvWow": "", "aov": 0, "newSignTopDaily": 0, "newSignMidDaily": 0, "newSignTopMTD": 0, "newSignMidMTD": 0, "activeRate": None, "cancelRate": None, "cancelRateWow": ""},
        {"city": "Western", "cm": "Feng Menglong", "dailyOrders": 0, "ordersWow": "", "gmv": 0, "gmvWow": "", "aov": 0, "newSignTopDaily": 0, "newSignMidDaily": 0, "newSignTopMTD": 0, "newSignMidMTD": 0, "activeRate": None, "cancelRate": None, "cancelRateWow": ""},
        {"city": "Santos", "cm": "Jaylin", "dailyOrders": 0, "ordersWow": "", "gmv": 0, "gmvWow": "", "aov": 0, "newSignTopDaily": 0, "newSignMidDaily": 0, "newSignTopMTD": 0, "newSignMidMTD": 0, "activeRate": None, "cancelRate": None, "cancelRateWow": ""},
    ],
    "metroTotal": {"dailyOrders": daily_orders[0]['total'] if daily_orders else 0, "ordersWow": "", "gmv": 0, "gmvWow": "", "aov": 0, "newSignTopDaily": 0, "newSignMidDaily": 0, "newSignTopMTD": 0, "newSignMidMTD": 0, "activeRate": None, "cancelRate": None, "cancelRateWow": ""},
    "insights": [
        {"icon": "📈", "text": f"Metro total orders {daily_orders[0]['total'] if daily_orders else 0} WoW (latest)."},
        {"icon": "🏪", "text": f"New sign yesterday: {new_signs[0]['topTier'] if new_signs else 0} Top + {new_signs[0]['midTier'] if new_signs else 0} Mid = {new_signs[0]['total'] if new_signs else 0} total."}
    ],
}
lines.append("export const dbrReport = " + json.dumps(dbr, indent=2) + ";\n")

# ddData
lines.append(f'''
export const ddData = {{
  date: "{latest_date_fmt}",
  targets: {{ mh: {{ dd3_15: 0.3, dd1_15: 0.65 }}, all: {{ dd3_15: 0.3, dd1_15: 0.5 }} }},
  metro: {{ mh: {{ shops: null, dd3_15_count: null, dd1_15_count: null, dd3_40_count: null, dd1_40_count: null, dd3_15: null, dd1_15: null, dd3_40: null, dd1_40: null }}, all: {{ shops: null, dd3_15_count: null, dd1_15_count: null, dd3_40_count: null, dd1_40_count: null, dd3_15: null, dd1_15: null, dd3_40: null, dd1_40: null }} }},
  cities: {{
    northeast: {{ label: "Northeast", labelCn: "东北区", cm: "danielalbuquerque", mh: {{ shops: null, dd3_15_count: null, dd1_15_count: null, dd3_40_count: null, dd1_40_count: null, dd3_15: null, dd1_15: null, dd3_40: null, dd1_40: null }}, all: {{ shops: null, dd3_15_count: null, dd1_15_count: null, dd3_40_count: null, dd1_40_count: null, dd3_15: null, dd1_15: null, dd3_40: null, dd1_40: null }}, bdms: [] }},
    western: {{ label: "Western", labelCn: "西区", cm: "fengmenglong", mh: {{ shops: null, dd3_15_count: null, dd1_15_count: null, dd3_40_count: null, dd1_40_count: null, dd3_15: null, dd1_15: null, dd3_40: null, dd1_40: null }}, all: {{ shops: null, dd3_15_count: null, dd1_15_count: null, dd3_40_count: null, dd1_40_count: null, dd3_15: null, dd1_15: null, dd3_40: null, dd1_40: null }}, bdms: [] }},
    santos: {{ label: "Santos", labelCn: "桑托斯", cm: "jaylin", mh: {{ shops: null, dd3_15_count: null, dd1_15_count: null, dd3_40_count: null, dd1_40_count: null, dd3_15: null, dd1_15: null, dd3_40: null, dd1_40: null }}, all: {{ shops: null, dd3_15_count: null, dd1_15_count: null, dd3_40_count: null, dd1_40_count: null, dd3_15: null, dd1_15: null, dd3_40: null, dd1_40: null }}, bdms: [] }},
    southern: {{ label: "Southern", labelCn: "南区", cm: "tianjie", mh: {{ shops: null, dd3_15_count: null, dd1_15_count: null, dd3_40_count: null, dd1_40_count: null, dd3_15: null, dd1_15: null, dd3_40: null, dd1_40: null }}, all: {{ shops: null, dd3_15_count: null, dd1_15_count: null, dd3_40_count: null, dd1_40_count: null, dd3_15: null, dd1_15: null, dd3_40: null, dd1_40: null }}, bdms: [] }},
  }}
}};
''')

output = "\n".join(lines)
with open('/mnt/openclaw/.openclaw/workspace/bp_data_new.js', 'w') as f:
    f.write(output)

print(f"Generated bp_data_new.js")
print(f"  Latest date: {latest_date_fmt}")
print(f"  Total orders 10d: {total_orders_10d}")
print(f"  Total new signs 10d: {total_new_signs_10d}")
print(f"  Total GMV 10d: R$ {total_gmv_10d:,.2f}")
print(f"  Weighted AOV: R$ {weighted_aov:,.2f}")
print(f"  CM rows: {len(cm_rows)}")
